version: "2"
run:
  timeout: 5m
  go: "1.25.1"
linters:
  default: standard
  enable:
    - govet
    - staticcheck
    - ineffassign
    - gocritic
    - misspell
    - goconst
    - prealloc
    - unconvert
    - unparam
  disable:
    - revive
    - unused
    - errcheck
