version: 2
run:
  timeout: 5m
  go: "1.25.1"
linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - gofmt
    - goimports
    - gosimple
    - gocritic
    - revive
    - misspell
    - goconst
    - prealloc
    - unconvert
    - unparam
issues:
  exclude-use-default: false
