version: "2"
run:
  timeout: 5m
  go: "1.25.1"
linters:
  default: none
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - gosimple
    - gocritic
    - revive
    - misspell
    - goconst
    - prealloc
    - unconvert
    - unparam
