services:
  app:
    build:
      context: .
      dockerfile: build/Dockerfile
    image: product-update-service-simulator:dev
    container_name: pus-app
    environment:
      - HTTP_ADDR=:8080
    expose:
      - "8080"
  itest:
    image: golang:1.25.1-bookworm
    container_name: pus-itest
    working_dir: /workspace
    depends_on:
      - app
    environment:
      - BASE_URL=http://app:8080
    volumes:
      - ./:/workspace
    entrypoint: ["/usr/local/go/bin/go"]
    command: ["test","./test/integration","-v"]
